version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_dbPatient
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: W8rty8zx
      POSTGRES_DB: PatientsDB
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
        
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "5050:80"
    depends_on:
      - db

  api:
    image: patients_api
    container_name: apiPatients
    build:
      context: ./PatientApi
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=PatientsDB;Username=postgres;Password=W8rty8zx
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data: